Add missing requirements gevent + greenlet
The Debian packages were not being able to run because the gevent module
couldn't be found:

  Traceback (most recent call last):
    File "/usr/bin/medusa", line 5, in <module>
      from medusa.medusacli import cli
    File "/usr/share/cassandra-medusa/lib/python3.7/site-packages/medusa/medusacli.py", line 17, in <module>
      from gevent import monkey
  ModuleNotFoundError: No module named 'gevent'