debian: Add missing build dependency for python3-venv
The build will just fail when it is not installed:

  make[1]: Entering directory '/build/cassandra-medusa-0.7.1'
  dh_virtualenv --python /usr/bin/python3 --preinstall=setuptools==40.3.0 --preinstall=pip==20.2.3 --preinstall=wheel --builtin-venv
  The virtual environment was not created successfully because ensurepip is not
  available.  On Debian/Ubuntu systems, you need to install the python3-venv
  package using the following command.

      apt-get install python3-venv

  You may need to use sudo with that command.  After installing the python3-venv
  package, recreate your virtual environment.

  Failing command: ['/build/cassandra-medusa-0.7.1/debian/cassandra-medusa/usr/share/cassandra-medusa/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

  Traceback (most recent call last):
    File "/usr/bin/dh_virtualenv", line 110, in <module>
      sys.exit(main() or 0)
    File "/usr/bin/dh_virtualenv", line 87, in main
      deploy.create_virtualenv()
    File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 157, in create_virtualenv
      subprocess.check_call(virtualenv)
    File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', 'debian/cassandra-medusa/usr/share/cassandra-medusa']' returned non-zero exit status 1
  make[1]: *** [debian/rules:28: override_dh_virtualenv] Error 1
  make[1]: Leaving directory '/build/cassandra-medusa-0.7.1'
  make: *** [debian/rules:25: binary] Error 2
  dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2